import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import DistributedTeamsSection from '../components/DistributedTeamsSection';
import HomepageHero from '../components/HomepageHero';
import Navigation from '../components/Navigation';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <HomepageHero />
      <DistributedTeamsSection />
    </>
  );
}
